Hooks:PostHook(HostNetworkSession, 'on_peer_entered_lobby', 'HostNetworkSessionOnPeerEnteredLobby_ANCR', function(self, peer)
	local peer_id = peer:id()
	DelayedCalls:Add('DelayedModAnnouncer' .. tostring(peer_id), 1, function()
		Announcer:AnnounceHostModTo(peer_id)
	end)
end)

Hooks:PostHook(HostNetworkSession, 'on_peer_sync_complete', 'HostNetworkSessionOnPeerSyncComplete_ANCR', function(self, peer, peer_id)
	DelayedCalls:Add('DelayedModAnnouncer' .. tostring(peer_id), 1, function()
		Announcer:AnnounceHostModTo(peer_id)
	end)
end)

Hooks:PostHook(ClientNetworkSession, 'on_entered_lobby', 'ClientNetworkSessionOnEnteredLobby_ANCR', function(self)
	DelayedCalls:Add('DelayedModAnnouncer1', 1, function()
		Announcer:AnnounceClientModTo(1)
	end)
end)

Hooks:PostHook(ClientNetworkSession, 'on_load_complete', 'ClientNetworkSessionOnLoadComplete_ANCR', function(self, simulation)
	DelayedCalls:Add('DelayedModAnnouncer1', 1, function()
		Announcer:AnnounceClientModTo(1)
	end)
end)
